version: '3.9'

services:
  mysql:
    image: bitnami/mysql:latest
    container_name: mysql_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passwordroot
      MYSQL_DATABASE: notas
      MYSQL_USER: docente1
      MYSQL_PASSWORD: pwdocente1
    volumes:
      - mysql_data:/bitnami/mysql
    networks:
      - dev-network

networks:
  dev-network:

volumes:
  mysql_data: